"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ANIMATE_NAME_Slide = exports.ANIMATE_NAME_Fade = exports.ANIMATE_TYPE = exports.ANIMATE_NAME = exports.globalBeforeEach = exports.useAnimationTypes = void 0;
var useAnimationTypes_1 = require("./store/animationTypes/useAnimationTypes");
Object.defineProperty(exports, "useAnimationTypes", { enumerable: true, get: function () { return useAnimationTypes_1.useAnimationTypes; } });
var global_beforeEach_1 = require("./router/global.beforeEach");
Object.defineProperty(exports, "globalBeforeEach", { enumerable: true, get: function () { return global_beforeEach_1.globalBeforeEach; } });
var types_1 = require("./constant/types");
Object.defineProperty(exports, "ANIMATE_NAME", { enumerable: true, get: function () { return types_1.ANIMATE_NAME; } });
Object.defineProperty(exports, "ANIMATE_TYPE", { enumerable: true, get: function () { return types_1.ANIMATE_TYPE; } });
Object.defineProperty(exports, "ANIMATE_NAME_Fade", { enumerable: true, get: function () { return types_1.ANIMATE_NAME_Fade; } });
Object.defineProperty(exports, "ANIMATE_NAME_Slide", { enumerable: true, get: function () { return types_1.ANIMATE_NAME_Slide; } });
