export {useAnimationTypes} from './store/animationTypes/useAnimationTypes'
export {globalBeforeEach} from './router/global.beforeEach'
export {SliceMeta} from './features/slide/sliceMeta'
export {ANIMATE_NAME, ANIMATE_TYPE, ANIMATE_NAME_Fade, ANIMATE_NAME_Slide} from './constant/types'
export {FadeMeta} from './features/fade/fadeMeta'
